### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by vasnt** [onsclom/canvas-text-editor#1]
1. will it be text editor but in canvas like fermat.ws or obsidian whiteboard?
2. feature request: supertag like in tana 
3. any AI feature planned?

**Comment by onsclom** [comment]
Hey, thanks for the questions! I’ll eventually make a README and change the repo name when my ideas are more solid. I’m still in an early experimental phase with this project.

When I named it canvas text editor I was actually being more literal. I’m using the `<canvas>` HTML element for everything and reimplementing a lot of the features you get from something like `<textarea>` from scratch. Did you know google docs does this to get better performance and customize-ability? Crazy right?!

I’m interested in making something similar to  a basic notepad program, except every action is smoothly animated. Instead of things discretely appearing and disappearing, the cursor and letters will be more continuous. I think this could make the experience of typing feel more natural and fun!

Here’s where I’m at now:

[twitter gif](https://twitter.com/onsclom/status/1668502000676515844?s=46&t=vnl-4eWZs52Ie3r_Y6Xy4A) 

Went on a bit of a tangent there, so to bring it back to your questions: these things aren’t really in the scope of this project. Unfortunately, I already have a lot of work cut out for me just recreating the basic features of something like `<textarea>` (keyboard hotkeys, selecting text, copy and paste, etc).

I hope that explanation was interesting and helpful. I’m curious, how did you find this project?

**Comment by vasnt** [comment]
project in one word is : awesome. Keep it up.
